services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      # ソースコードをマウント（開発時の変更を即座に反映）
      - .:/app:delegated
      # node_modulesとvendor/bundleはボリュームで分離（パフォーマンス向上）
      - node_modules:/app/node_modules
      - bundle:/usr/local/bundle
      # Slidevプロジェクトとビルド成果物を永続化
      - slidev_projects:/app/slidev_projects
      - public_slides:/app/public/slides
      # データベースを永続化
      - db:/app/db
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=true
      - NODE_OPTIONS=--max-old-space-size=4096
    stdin_open: true
    tty: true
    # メモリ制限を設定（Slidevのビルドに十分なメモリを確保）
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 2G

volumes:
  node_modules:
  bundle:
  slidev_projects:
  public_slides:
  db:
